### ISSUE TITLE
Feature Request : Tagging support for IAM users and Roles

### ISSUE THREAD

**Issue by rams3sh** [mpostument/awstaghelper#14]
Hey Team

First of all , good work on the tool. Its really nice to have such a user friendly and simple CSV based tag compliance checker and remediation tool.
I have a use case for tagging IAM Users and Roles for security compliance purposes and recording the type of user (Human / Service User) etc ... !! 

It would be nice to have the support for IAM Users and Roles as well !! 

Thanks

**Comment by mpostument** [comment]
Hello, I am glad this tool becomes useful for you. IAM was the next item on my list. I think I can start working on it tomorrow

**Comment by mpostument** [comment]
Iam role and user support added in version https://github.com/mpostument/awstaghelper/releases/tag/0.14.0
